spring:
  application:
    name: file-manager
  main:
    banner-mode: off
  rabbitmq:
    host: localhost
    port: 5671
    username: haccp
    password: MySecretPassword
    template:
      mandatory: true

  jmx:
    enabled: true

  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/file
    username: file
    password: MySecretPassword

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.types.print.banner: false
    show-sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          enabled: true
          include: rabbit
        liveness:
          enabled: true
          include: rabbit


server:
  port: 8081
  servlet:
    context-path: /api/file_manager

amqp:
  modules:
    - name: document-registration
      queues:
        - request: file.upload.request
          response: file.upload.response

file:
  folder-uri: ${HOME}/tmp/final
  url:
    lifetime: 30
    base: 'http://localhost:8081/api/file_manager/download/'

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html